format = """
$username$hostname$python$directory$git_branch$git_status$time
$character
"""


[username]
style_user = "bold yellow"
show_always = true
format = "ğŸ’» [$user]($style)"

[hostname]
ssh_only = false
format = "@[$hostname](bold blue) "

[directory]
style = "bold green"
format = "ğŸ“ [$path]($style) "


[time]
disabled = false
format = "ğŸ•’ [$time](dimmed white) "
time_format = "%H:%M"
utc_time_offset = "local"

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bold red)"
format = "$symbol "

[python]
format = '[ğŸ $virtualenv]($style) '
style = 'bold purple'
detect_extensions = []
detect_files = []
detect_folders = []

[git_branch]
symbol = "ğŸŒ± "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "dimmed red"
conflicted = "âš”ï¸ "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
untracked = "ğŸ›¤ï¸ ${count} "
stashed = "ğŸ“¦ ${count} "
modified = "ğŸ“ ${count} "
staged = "â• ${count} "
renamed = "ğŸ” ${count} "
deleted = "âŒ ${count} "
